### ISSUE TITLE
Setup more robust project documentation

### ISSUE THREAD

**Issue by marcoceppi** [cloud-custodian/pytest-terraform#11]
Would be great to help with others looking to adopt this library / pattern to get documentation generated from source and uploaded to RTD

**Comment by kapilt** [comment]
yeah.. would like to kick the tires with mkdocs here instead of sphinx, which has been a bit painful tbh at least with custodian.

**Comment by marcoceppi** [comment]
Sounds like a good place to pilot that. I can start to scaffold something out in a draft PR for bolting mkdocs + readthedocs.com

**Comment by kapilt** [comment]
GitHub pages might be a nice alternative vs read the docs, also worth a look at hugo

**Comment by kapilt** [comment]
feels like we're good on the readme  covering usage modes now.
