### ISSUE TITLE
`find_binary` should be platform aware

### ISSUE THREAD

**Issue by stefangordon** [cloud-custodian/pytest-terraform#40]
Do we want Win32 support?

Path var delimiter (`;` vs `:`) and file extension (`.exe`).

**Comment by marcoceppi** [comment]
Probably, for now a user can set `--tf-binary` (`dest_tf_binary`) to support Windows this is more a papercut in UX for Windows than a lack of support for Windows.

However, I will admit we don't run Windows unit tests today nor do any of the maintainers to date validate UX on Windows. To answer you question, yes - I think we want to support all developers using the tool on the platform they are on (within reason - if you're having issues with a Sun SPARC system we may say no but Windows is very reasonable).
