### ISSUE TITLE
Compatibility with Terraspace

### ISSUE THREAD

**Issue by duncanwraight** [cloud-custodian/pytest-terraform#60]
Hi folks

Is there any way we could use `pytest-terraform` with Terraspace?

It's a Ruby wrapper to allow layering of configuration. Makes TF repositories cleaner and more DRY-friendly: https://terraspace.cloud/

Instead of `terraform plan`, `terraform apply` etc. we use `terraspace up <<stack name>>`, e.g. `terraform up eks-cluster`.

Could we override the executable commands used? Or could we run `terraspace up` _first_ before running the `pytest` tests?

**Comment by kapilt** [comment]
Try using --tf-binary config option to try it with the terraspace wrapper, however whether it works depends on the compatibility of terraspace to terraform, and not something we would directly test or support.
