### ISSUE TITLE
Pytest-Terraform for GCP

### ISSUE THREAD

**Issue by th3gentleman-MubinGirach** [cloud-custodian/pytest-terraform#61]
Hey there ! 

I tried using pytest-terraform for testing out my GCP modules but was stuck at the initial phase due to which my python script is not able to locate the modules , I further request the maintainers/contributors to assist me with the following queries 

- What should be the file  or folder structure to be maintained with respect to the python script

- Any Repos / reference for examples based on GCP module based test cases

**Comment by kapilt** [comment]
default directory for the terraform, is a directory named `terraform` relative to the test modules. so a typical setup is

```
tests/
    test_infra.py
    terraform/
         root_module_1/
         root_module_2/
```

pytest-terraform is terraform provider agnostic.
